import { Clinic, ClinicType, Employee, EmploymentType, StaffRole, SystemTool } from './types';

export const CLINICS: Clinic[] = [
  {
    id: 'c1',
    name: 'ホワイトデンタルクリニック 本院',
    type: ClinicType.HQ,
    address: '東京都港区六本木1-1-1',
    chairs: 8,
    phone: '03-1234-5678',
  },
  {
    id: 'c2',
    name: 'ホワイトデンタル 横浜分院',
    type: ClinicType.BRANCH,
    address: '神奈川県横浜市西区みなとみらい2-2-2',
    chairs: 5,
    phone: '045-1234-5678',
  },
  {
    id: 'c3',
    name: 'ホワイトデンタル 大宮分院',
    type: ClinicType.BRANCH,
    address: '埼玉県さいたま市大宮区3-3-3',
    chairs: 4,
    phone: '048-1234-5678',
  },
];

export const SYSTEMS: SystemTool[] = [
  {
    id: 's1',
    name: 'Google Workspace',
    category: 'Groupware',
    url: 'https://admin.google.com',
    monthlyCostPerUser: 1360,
    baseMonthlyCost: 0,
    renewalDate: '2024-12-01',
    adminOwner: '佐藤 太郎',
    vendorContact: 'Google Direct',
    status: 'Active',
    issues: ['共有ドライブの権限が複雑化している'],
  },
  {
    id: 's2',
    name: 'Apotool & Box',
    category: 'Reservation',
    url: 'https://apotool.jp',
    monthlyCostPerUser: 0,
    baseMonthlyCost: 30000,
    renewalDate: '2024-09-30',
    adminOwner: '鈴木 花子',
    vendorContact: 'Support Desk: 03-xxxx-xxxx',
    status: 'Active',
    issues: [],
  },
  {
    id: 's3',
    name: 'Slack',
    category: 'Communication',
    url: 'https://slack.com',
    monthlyCostPerUser: 960,
    baseMonthlyCost: 0,
    renewalDate: '2025-01-15',
    adminOwner: '佐藤 太郎',
    vendorContact: 'Self-serve',
    status: 'Review',
    issues: ['無料プランに戻すか検討中'],
  },
  {
    id: 's4',
    name: 'MoneyForward クラウド',
    category: 'Accounting',
    url: 'https://moneyforward.com',
    monthlyCostPerUser: 0,
    baseMonthlyCost: 5000,
    renewalDate: '2024-06-30',
    adminOwner: '事務長',
    vendorContact: 'Sales Rep A',
    status: 'Active',
    issues: [],
  },
];

export const EMPLOYEES: Employee[] = [
  {
    id: 'e1',
    firstName: '太郎',
    lastName: '佐藤',
    clinicId: 'c1',
    role: StaffRole.SYSADMIN,
    employmentType: EmploymentType.FULL_TIME,
    email: 'taro.sato@whitedental.jp',
    joinDate: '2020-04-01',
    assignedSystems: ['s1', 's3'],
    status: 'Active',
  },
  {
    id: 'e2',
    firstName: '花子',
    lastName: '鈴木',
    clinicId: 'c1',
    role: StaffRole.DH,
    employmentType: EmploymentType.FULL_TIME,
    email: 'hanako.suzuki@whitedental.jp',
    joinDate: '2021-04-01',
    assignedSystems: ['s1', 's3'],
    status: 'Active',
  },
  {
    id: 'e3',
    firstName: '一郎',
    lastName: '田中',
    clinicId: 'c2',
    role: StaffRole.DR,
    employmentType: EmploymentType.PART_TIME,
    email: 'ichiro.tanaka@whitedental.jp',
    joinDate: '2022-10-01',
    assignedSystems: ['s1'],
    status: 'Active',
  },
  {
    id: 'e4',
    firstName: '次郎',
    lastName: '山田',
    clinicId: 'c3',
    role: StaffRole.DA,
    employmentType: EmploymentType.PART_TIME,
    email: 'jiro.yamada@whitedental.jp',
    joinDate: '2023-01-15',
    assignedSystems: ['s1'],
    status: 'Active',
  },
  {
    id: 'e5',
    firstName: '愛',
    lastName: '高橋',
    clinicId: 'c1',
    role: StaffRole.ADMIN,
    employmentType: EmploymentType.FULL_TIME,
    email: 'ai.takahashi@whitedental.jp',
    joinDate: '2019-04-01',
    assignedSystems: ['s1', 's3', 's4'],
    status: 'Active',
  },
  {
    id: 'e6',
    firstName: '健太',
    lastName: '小林',
    clinicId: 'c2',
    role: StaffRole.DR,
    employmentType: EmploymentType.FULL_TIME,
    email: 'kenta.kobayashi@whitedental.jp',
    joinDate: '2023-04-01',
    assignedSystems: ['s1', 's3'],
    status: 'Active',
  },
];

export const GOVERNANCE_RULES = {
  naming: [
    { rule: 'メールアドレス', pattern: '{姓(ローマ字)}.{名(ローマ字)}@domain.jp', example: 'taro.sato@whitedental.jp' },
    { rule: 'PC端末名', pattern: '{医院コード}-{職種}-{番号}', example: 'HQ-DR-01' },
  ],
  security: [
    { title: '患者情報(PHI)の取り扱い', content: '患者氏名やカルテ番号を含むファイルは、必ず「患者情報」フォルダに保存し、パスワードをかけること。' },
    { title: '共有フォルダ権限', content: '「経営管理」フォルダは院長・事務長のみアクセス可能とする。各医院フォルダは当該医院のスタッフのみアクセス可。' },
  ]
};