import React from 'react';
import { Database, Copy, Check, Terminal } from 'lucide-react';

export const SetupGuide: React.FC = () => {
  const [copied, setCopied] = React.useState(false);

  const sqlCode = `
-- 既存のテーブルがある場合は削除（開発用）
drop table if exists public.employee_assigned_systems;
drop table if exists public.employees;
drop table if exists public.systems;
drop table if exists public.clinics;
drop table if exists public.tenants;

-- テナントテーブル
create table public.tenants (
  id text primary key,
  name text,
  plan text,
  status text,
  owner_email text,
  governance jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 医院テーブル (ON DELETE CASCADE追加)
create table public.clinics (
  id text primary key,
  tenant_id text references public.tenants(id) on delete cascade,
  name text,
  type text,
  address text,
  phone text,
  chairs integer
);

-- システムテーブル (ON DELETE CASCADE追加)
create table public.systems (
  id text primary key,
  tenant_id text references public.tenants(id) on delete cascade,
  name text,
  category text,
  url text,
  status text,
  base_monthly_cost integer,
  monthly_cost_per_user integer,
  renewal_date text,
  admin_owner text,
  vendor_contact text,
  issues text[],
  contract_url text
);

-- 従業員テーブル (ON DELETE CASCADE追加)
create table public.employees (
  id text primary key,
  tenant_id text references public.tenants(id) on delete cascade,
  clinic_id text references public.clinics(id) on delete set null,
  first_name text,
  last_name text,
  email text,
  role text,
  employment_type text,
  status text,
  join_date text
);

-- 従業員とシステムの中間テーブル (ON DELETE CASCADE追加)
create table public.employee_assigned_systems (
  id bigint generated by default as identity primary key,
  employee_id text references public.employees(id) on delete cascade,
  system_id text references public.systems(id) on delete cascade
);

-- ストレージバケットの作成（存在しない場合のみエラー無視などで対応が必要だが、SQLエディタで実行前提）
insert into storage.buckets (id, name, public) values ('system-assets', 'system-assets', true)
on conflict (id) do nothing;

-- RLSポリシー（開発用: 全許可）
alter table public.tenants enable row level security;
create policy "Public Access" on public.tenants for all using (true);

alter table public.clinics enable row level security;
create policy "Public Access" on public.clinics for all using (true);

alter table public.systems enable row level security;
create policy "Public Access" on public.systems for all using (true);

alter table public.employees enable row level security;
create policy "Public Access" on public.employees for all using (true);

alter table public.employee_assigned_systems enable row level security;
create policy "Public Access" on public.employee_assigned_systems for all using (true);
`.trim();

  const handleCopy = () => {
    navigator.clipboard.writeText(sqlCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-screen bg-slate-900 text-white p-8 flex flex-col items-center justify-center">
      <div className="max-w-4xl w-full">
        <div className="flex items-center gap-3 mb-6">
          <Database className="text-red-500 w-8 h-8" />
          <h1 className="text-2xl font-bold">データベースの再構築を推奨します</h1>
        </div>
        
        <p className="text-slate-300 mb-8 text-lg">
          データの削除機能や整合性を保つため、テーブル定義（SQL）を更新しました。<br/>
          お手数ですが、以下のSQLをSupabaseの <span className="font-mono bg-slate-800 px-2 py-1 rounded">SQL Editor</span> で実行し、テーブルを作り直してください。<br/>
          <span className="text-red-400 font-bold text-sm">※既存のデータはすべてリセットされます。</span>
        </p>

        <div className="bg-slate-950 rounded-xl border border-slate-800 overflow-hidden shadow-2xl">
          <div className="flex justify-between items-center px-4 py-3 bg-slate-900 border-b border-slate-800">
            <div className="flex items-center gap-2 text-sm text-slate-400">
              <Terminal size={16} />
              <span>setup_v2.sql</span>
            </div>
            <button 
              onClick={handleCopy}
              className={`flex items-center gap-2 px-3 py-1.5 rounded text-sm font-medium transition-colors ${
                copied ? 'bg-green-600 text-white' : 'bg-slate-800 hover:bg-slate-700 text-slate-300'
              }`}
            >
              {copied ? <Check size={16} /> : <Copy size={16} />}
              {copied ? 'コピーしました' : 'SQLをコピー'}
            </button>
          </div>
          <pre className="p-4 overflow-x-auto text-sm font-mono leading-relaxed text-blue-300 max-h-96">
            <code>{sqlCode}</code>
          </pre>
        </div>

        <div className="mt-8 text-center">
          <button 
            onClick={() => window.location.reload()} 
            className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-bold transition-colors"
          >
            ページを再読み込み
          </button>
        </div>
      </div>
    </div>
  );
};