import React, { useState } from 'react';
import { Database, Copy, Check, Terminal, RefreshCw, ArrowRightLeft, ShieldAlert, X } from 'lucide-react';

interface SetupGuideProps {
  onClose?: () => void;
}

export const SetupGuide: React.FC<SetupGuideProps> = ({ onClose }) => {
  const [copied, setCopied] = useState(false);
  const [mode, setMode] = useState<'migration' | 'reset' | 'admin_func'>('admin_func');

  const adminFuncSql = `
-- スーパー管理者用のユーザー完全削除関数
-- 注意: この関数は admin@saas-provider.com からのリクエストのみを受け付けます

create or replace function public.admin_delete_user(target_email text)
returns void
language plpgsql
security definer -- 特権モードで実行
as $$
declare
  requesting_user_email text;
begin
  -- 実行者のメールアドレスを取得
  select auth.jwt() ->> 'email' into requesting_user_email;

  -- 権限チェック (admin@saas-provider.com 以外は実行不可)
  if requesting_user_email != 'admin@saas-provider.com' then
    raise exception 'Forbidden: Only Super Admin can execute this function.';
  end if;

  -- auth.users から削除 (これによりログインできなくなり、同じメアドで再登録可能になる)
  delete from auth.users where email = target_email;
end;
$$;
`.trim();

  const migrationSqlCode = `
-- 既存のテーブルにカラムを追加（データは保持されます）

-- account_typeカラムを追加 (デフォルト: Google Workspace)
alter table public.employees 
add column if not exists account_type text default 'Google Workspace';

-- managed_passwordカラムを追加
alter table public.employees 
add column if not exists managed_password text;

-- 念のため権限を再適用
grant all on public.employees to anon, authenticated, service_role;
`.trim();

  const resetSqlCode = `
-- 既存のテーブルがある場合は削除（開発用）
drop table if exists public.employee_assigned_systems;
drop table if exists public.employees;
drop table if exists public.systems;
drop table if exists public.clinics;
drop table if exists public.tenants;

-- テナントテーブル
create table public.tenants (
  id text primary key,
  name text,
  plan text,
  status text,
  owner_email text,
  governance jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 医院テーブル (ON DELETE CASCADE追加)
create table public.clinics (
  id text primary key,
  tenant_id text references public.tenants(id) on delete cascade,
  name text,
  type text,
  address text,
  phone text,
  chairs integer
);

-- システムテーブル (ON DELETE CASCADE追加)
create table public.systems (
  id text primary key,
  tenant_id text references public.tenants(id) on delete cascade,
  name text,
  category text,
  url text,
  status text,
  base_monthly_cost integer,
  monthly_cost_per_user integer,
  renewal_date text,
  admin_owner text,
  vendor_contact text,
  issues text[],
  contract_url text
);

-- 従業員テーブル (ON DELETE CASCADE追加)
-- account_type, managed_passwordを追加
create table public.employees (
  id text primary key,
  tenant_id text references public.tenants(id) on delete cascade,
  clinic_id text references public.clinics(id) on delete set null,
  first_name text,
  last_name text,
  email text,
  role text,
  employment_type text,
  status text,
  join_date text,
  account_type text default 'Google Workspace',
  managed_password text
);

-- 従業員とシステムの中間テーブル (ON DELETE CASCADE追加)
create table public.employee_assigned_systems (
  id bigint generated by default as identity primary key,
  employee_id text references public.employees(id) on delete cascade,
  system_id text references public.systems(id) on delete cascade
);

-- ストレージバケットの作成
insert into storage.buckets (id, name, public) values ('system-assets', 'system-assets', true)
on conflict (id) do nothing;

-- RLSポリシー（開発用: 全許可）
alter table public.tenants enable row level security;
create policy "Public Access" on public.tenants for all using (true);

alter table public.clinics enable row level security;
create policy "Public Access" on public.clinics for all using (true);

alter table public.systems enable row level security;
create policy "Public Access" on public.systems for all using (true);

alter table public.employees enable row level security;
create policy "Public Access" on public.employees for all using (true);

alter table public.employee_assigned_systems enable row level security;
create policy "Public Access" on public.employee_assigned_systems for all using (true);
`.trim();

  let activeCode = '';
  if (mode === 'migration') activeCode = migrationSqlCode;
  else if (mode === 'reset') activeCode = resetSqlCode;
  else activeCode = adminFuncSql;

  const handleCopy = () => {
    navigator.clipboard.writeText(activeCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-screen bg-slate-900 text-white p-8 flex flex-col items-center justify-center relative">
      {onClose && (
        <button 
          onClick={onClose}
          className="absolute top-6 right-6 p-2 bg-slate-800 rounded-full text-slate-400 hover:text-white hover:bg-slate-700 transition-colors"
        >
          <X size={24} />
        </button>
      )}

      <div className="max-w-4xl w-full">
        <div className="flex items-center gap-3 mb-6">
          <Database className="text-blue-500 w-8 h-8" />
          <h1 className="text-2xl font-bold">データベース更新 / 管理機能追加</h1>
        </div>
        
        <p className="text-slate-300 mb-8 text-lg">
          ユーザーを「完全に削除」するには、SupabaseのAuthテーブルへのアクセス権限を持つ関数を作成する必要があります。<br/>
          <strong className="text-white">「管理者用関数」</strong>タブを選択し、SQLを実行してください。
        </p>

        <div className="flex space-x-2 mb-4 bg-slate-800 p-1 rounded-lg inline-flex">
          <button 
            onClick={() => setMode('admin_func')}
            className={`flex items-center px-4 py-2 rounded-md font-bold transition-all ${
              mode === 'admin_func' 
                ? 'bg-purple-600 text-white shadow-lg' 
                : 'text-slate-400 hover:bg-slate-700'
            }`}
          >
            <ShieldAlert size={16} className="mr-2" />
            管理者用関数 (必須)
          </button>
          <button 
            onClick={() => setMode('migration')}
            className={`flex items-center px-4 py-2 rounded-md font-bold transition-all ${
              mode === 'migration' 
                ? 'bg-blue-600 text-white shadow-lg' 
                : 'text-slate-400 hover:bg-slate-700'
            }`}
          >
            <ArrowRightLeft size={16} className="mr-2" />
            マイグレーション
          </button>
          <button 
            onClick={() => setMode('reset')}
            className={`flex items-center px-4 py-2 rounded-md font-bold transition-all ${
              mode === 'reset' 
                ? 'bg-red-600 text-white shadow-lg' 
                : 'text-slate-400 hover:bg-slate-700'
            }`}
          >
            <RefreshCw size={16} className="mr-2" />
            リセット
          </button>
        </div>

        <div className="bg-slate-950 rounded-xl border border-slate-800 overflow-hidden shadow-2xl relative">
          <div className="flex justify-between items-center px-4 py-3 bg-slate-900 border-b border-slate-800">
            <div className="flex items-center gap-2 text-sm text-slate-400">
              <Terminal size={16} />
              <span>
                {mode === 'admin_func' ? 'create_admin_function.sql' : 
                 mode === 'migration' ? 'migration_v1.sql' : 'setup_full.sql'}
              </span>
            </div>
            <button 
              onClick={handleCopy}
              className={`flex items-center gap-2 px-3 py-1.5 rounded text-sm font-medium transition-colors ${
                copied ? 'bg-green-600 text-white' : 'bg-slate-800 hover:bg-slate-700 text-slate-300'
              }`}
            >
              {copied ? <Check size={16} /> : <Copy size={16} />}
              {copied ? 'コピーしました' : 'SQLをコピー'}
            </button>
          </div>
          
          <div className="relative">
            <pre className="p-4 overflow-x-auto text-sm font-mono leading-relaxed text-blue-300 max-h-96">
              <code>{activeCode}</code>
            </pre>
          </div>
        </div>

        <div className="mt-8 text-center">
          {onClose ? (
             <button 
             onClick={onClose} 
             className="px-6 py-3 bg-slate-700 hover:bg-slate-600 text-white rounded-lg font-bold transition-colors"
           >
             ダッシュボードに戻る
           </button>
          ) : (
            <>
              <p className="text-slate-400 text-sm mb-4">SQLの実行が完了したら、再読み込みしてください</p>
              <button 
                onClick={() => window.location.reload()} 
                className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-bold transition-colors"
              >
                ページを再読み込み
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  );
};